#!/system/bin/sh
# - sysctl -p
# coldblue_ : cpu settings

echo 'ondemand' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

echo '245760' >/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

echo '1024000' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

echo "85" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold

echo "60000" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate

echo "1" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor

echo "10" > /sys/devices/system/cpu/cpufreq/ondemand/down_differential

echo "40" > /sys/devices/system/cpu/cpufreq/ondemand/freq_step